In [28]:
import numpy as np
import pandas as pd
from numpy.linalg import inv
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [29]:
# Question-1

In [30]:
NUM_ITERATIONS = 5
INIT_WEIGHTS = np.array([0, 6, 6])

samples = np.array([
    [1, 2, 0],  
    [1, 2, 2],
    [1, 0, 2]
])
targets = np.array([1, 1, -1]) 

current_weights = INIT_WEIGHTS.copy()

for iteration in range(NUM_ITERATIONS):
    print(f"\nCycle {iteration + 1}")
    print(f"Current Parameters: {current_weights}")
    
    for idx, observation in enumerate(samples):
        decision_score = np.dot(current_weights, observation)
        predicted_class = 1 if decision_score >= 0 else -1
        
        if predicted_class != targets[idx]:
            current_weights += targets[idx] * observation
            print(f"Sample {idx+1} New weights: {current_weights}")
           
print("\n Final Model Parameters")
print(current_weights)


Cycle 1
Current Parameters: [0 6 6]
Sample 3 New weights: [-1  6  4]

Cycle 2
Current Parameters: [-1  6  4]
Sample 3 New weights: [-2  6  2]

Cycle 3
Current Parameters: [-2  6  2]
Sample 3 New weights: [-3  6  0]

Cycle 4
Current Parameters: [-3  6  0]

Cycle 5
Current Parameters: [-3  6  0]

 Final Model Parameters
[-3  6  0]


In [31]:
# Question-2(a)

In [32]:
input_features = np.array([
    [1, 3, 2],  
    [1, 2, 2],   
    [1, 1, -1],   
    [1, -1, -3]  
])

target_values = np.array([
    [3],         
    [1],          
    [-1],         
    [-3]          
])

feature_transpose = input_features.T

covariance_matrix = feature_transpose @ input_features
covariance_inverse = np.linalg.inv(covariance_matrix)

projection_components = feature_transpose @ target_values

optimal_weights = covariance_inverse @ projection_components

print("Covariance Matrix (XᵀX):\n", covariance_matrix)
print("\nInverse Covariance Matrix (XᵀX)⁻¹:\n", covariance_inverse)
print("\nProjection Vector (XᵀY):\n", projection_components)
print("\nOptimized Parameters:\n", optimal_weights)

Covariance Matrix (XᵀX):
 [[ 4  5  0]
 [ 5 15 12]
 [ 0 12 18]]

Inverse Covariance Matrix (XᵀX)⁻¹:
 [[ 2.33333333 -1.66666667  1.11111111]
 [-1.66666667  1.33333333 -0.88888889]
 [ 1.11111111 -0.88888889  0.64814815]]

Projection Vector (XᵀY):
 [[ 0]
 [13]
 [18]]

Optimized Parameters:
 [[-1.66666667]
 [ 1.33333333]
 [ 0.11111111]]


In [33]:
#Question 2 (b)

In [34]:
predictor_matrix = np.array([
    [1, 3, 2],   
    [1, 2, 2],
    [1, 1, -1],
    [1, -1, -3]
])

response_vector = np.array([3, 1, -1, -3])


reg_estimator = LinearRegression(fit_intercept=False)  


reg_estimator.fit(predictor_matrix, response_vector)

learned_parameters = reg_estimator.coef_.reshape(-1, 1)

print("\n Weight Vector:")
print(learned_parameters)


 Weight Vector:
[[-1.66666667]
 [ 1.33333333]
 [ 0.11111111]]


In [35]:
# Question-3

In [36]:
class_A_samples = np.array([[4, 3], [2, 2]])     
class_B_samples = np.array([[1, 1], [-2, -1]]) 

centroid_A = np.mean(class_A_samples, axis=0)  
centroid_B = np.mean(class_B_samples, axis=0)  

print("Centroid of Class A:", centroid_A)
print("Centroid of Class B:", centroid_B)


A_deviations = class_A_samples - centroid_A  
B_deviations = class_B_samples - centroid_B  

dispersion_A = np.dot(A_deviations.T, A_deviations)  
dispersion_B = np.dot(B_deviations.T, B_deviations)  

total_dispersion = dispersion_A + dispersion_B

print("\nWithin-Class Scatter Matrix for Class A:\n", dispersion_A)
print("\nWithin-Class Scatter Matrix for Class B:\n", dispersion_B)
print("\nTotal Within-Class Scatter Matrix (Sw):\n", total_dispersion)

class_separation = (centroid_A - centroid_B).reshape(-1, 1) 

projection_params = np.linalg.pinv(total_dispersion) @ class_separation

print("\nOptimal Projection Vector w:\n", projection_params.flatten())

Centroid of Class A: [3.  2.5]
Centroid of Class B: [-0.5  0. ]

Within-Class Scatter Matrix for Class A:
 [[2.  1. ]
 [1.  0.5]]

Within-Class Scatter Matrix for Class B:
 [[4.5 3. ]
 [3.  2. ]]

Total Within-Class Scatter Matrix (Sw):
 [[6.5 4. ]
 [4.  2.5]]

Optimal Projection Vector w:
 [-5.  9.]


In [37]:
# Question - 4

In [41]:
clinical_data = pd.read_csv('heart_disease_data.txt', header=0)  

clinical_data = clinical_data.apply(pd.to_numeric, errors='coerce')

X = clinical_data.iloc[:, :-1].values  
y = clinical_data.iloc[:, -1].values   

imputer = SimpleImputer(strategy="mean")
X = imputer.fit_transform(X)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

perceptron_model = Perceptron(max_iter=1000, eta0=0.1, random_state=42)
perceptron_model.fit(X_scaled, y)

lda_model = LinearDiscriminantAnalysis()
lda_model.fit(X_scaled, y)

print("\nPerceptron Weight Vector (w):")
print(perceptron_model.coef_[0])

print("\nLDA Weight Vector (w):")
print(lda_model.coef_[0])


Perceptron Weight Vector (w):
[ 0.11431283  0.32071349  0.26062734  0.11602958  0.36455355  0.07731113
  0.63424637 -0.11135151  0.13093073  0.29950232  0.03251153  0.13344626
  0.37948656]

LDA Weight Vector (w):
[-0.03852874  0.56924403  1.18820526 -0.53508891  0.82835629 -0.02675105
  0.66142493 -0.39773726  0.14991417  0.88489601  0.1723214   0.90412537
  1.91808161]


In [11]:
import pandas as pd
import numpy as np
import sklearn.linear_model as Perceptron

In [2]:
df = pd.read_csv('heart_disease_data.txt')

In [3]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0


In [6]:
data = df.to_numpy()
x = data[:, :-1]
y= data[:, -1]

In [7]:
print("Shape of X:", x.shape)
print("Shape of Y:", y.shape)

Shape of X: (100, 13)
Shape of Y: (100,)


In [13]:
perceptron = lm.Perceptron(max_iter=1000)
perceptron.fit(x,y)

Perceptron()

In [14]:
perceptron.coef_

array([[  731. ,    67. ,   197. ,   325. ,    23. ,   -10. ,   116. ,
        -1187. ,    59. ,   189.9,    93. ,   159. ,   508. ]])

In [15]:
perceptron.intercept_

array([6.])

In [16]:
import sklearn.discriminant_analysis as da

In [17]:
lda = da.LinearDiscriminantAnalysis()

In [18]:
lda.fit(x,y)

LinearDiscriminantAnalysis()

In [19]:
lda.coef_

array([[-0.00473584,  1.26780721,  1.30117132, -0.03437771,  0.01697281,
        -0.07954438,  0.66800376, -0.01986038,  0.32713953,  0.78643444,
         0.25465599,  1.02247583,  0.99167057]])

In [20]:
lda.intercept_

array([-9.59068692])

In [21]:
# Question - 4